[package]
name = "brc"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = "line-tables-only"

[dependencies]
ahash = "0.8.12"
memmap2 = "0.9.9"
pprof = { version = "0.15.0", features = ["protobuf", "prost-codec"] }
